USE LibraryDB
GO

CREATE PROC StoredProcedure2
AS
BEGIN
	SELECT No_Of_Copies, BranchName
		FROM BOOK_COPIES
		INNER JOIN BOOK ON BOOK.BookId = BOOK_COPIES.BookId
		INNER JOIN LIBRARY_BRANCH ON LIBRARY_BRANCH.BranchId = BOOK_COPIES.BranchId
		WHERE Title = 'The Lost Tribe'
END
GO