USE LibraryDB
GO

CREATE PROC StoredProcedure4
AS
BEGIN
	SELECT Title, MemberName, MemberAddress
		FROM BOOK_LOANS LOANS
		INNER JOIN BORROWER MEMBER ON MEMBER.CardNo = LOANS.CardNo
		INNER JOIN BOOK ON BOOK.BookId = LOANS.BookId
		INNER JOIN LIBRARY_BRANCH BRANCH ON BRANCH.BranchId = LOANS.BranchId
		WHERE BranchName = 'Sharpstown' AND DueDate = (SELECT CONVERT(date, GETDATE()))
END
GO